name: taam
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # API CLIENT
  dio: ^4.0.6
  
  # STATE MANAGEMENT
  provider: ^6.0.3

  # ICON
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.1

  # UTILS
  flutter_dotenv: ^5.0.2
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.0.15
  # flex_color_scheme: ^6.0.1
  device_preview: ^1.1.0
  connectivity_plus: ^2.3.7
  mask_text_input_formatter: ^2.4.0

  # Model Management
  json_serializable: ^6.4.1
  supabase_flutter: ^0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.development
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
